DROP DATABASE IF EXISTS db_produit;
CREATE DATABASE db_produit;
USE db_produit;
CREATE TABLE IF NOT EXISTS produits (
		 ID_PRODUIT  int(11) NOT NULL AUTO_INCREMENT,
		 NOM_PRODUIT VARCHAR(25) NOT NULL,
		 PRIX double NOT NULL,
		 PRIMARY KEY (ID_PRODUIT)
 )ENGINE = InnoDB DEFAULT CHARSET = latin1 AUTO_INCREMENT = 1;